### ISSUE TITLE
How can I compilee it ?

### ISSUE THREAD

**Issue by rusyasoft** [packetngin/rtos#196]
I'm having trouble at compiling because of module2.h file is missing. I think it is somehow related to empty folders cmocka and grub.

Is there anything I'm missing here ?

**Comment by Xeite** [comment]
We have additional sub modules to build, and it was required for user to add their own SSH key to github since we keep URL of our sub modules by SSH protocol. I thought it was not appropriate for normal user , so deleted this limitation by 1cb2017

Besides, we have one more special sub module called  "rtos_commerical"  which normal user cannot access. So, actually until now nobody can build kernel without access to this sub module. I also deleted this restriction by c2e8f6c.

Now to build kernel, only thing you have to do is to fetch sub modules and build them manally, and make in root directory.

Detailed instructions are described in rtos/doc/setup.md.
